name = "ac6-assemble-tool"
compatibility_date = "2024-09-10"
main = "./.svelte-kit/cloudflare/_worker.js"

[vars]
# Environment variables can be defined here

# Development configuration
[env.development]
vars = { ENVIRONMENT = "development" }

# Production configuration  
[env.production]
vars = { ENVIRONMENT = "production" }