name: Lint & Fix Markdown Files

on:
  pull_request:
    branches: ["*"]
    paths:
      - "*.md"
      - ".github/**/*.md"
      - "docs/**/*.md"
      - "packages/**/*.md"
      - ".github/workflows/lint-docs.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: ".tool-versions"
      - name: setup
        run: bun install --frozen-lockfile

      - name: lint documents
        run: bun run docs format

      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@v7-next
        with:
          commit_message: Auto commit with fmt
          branch: ${{ github.head_ref }}
